export enum Icon {
  AI = 'AI',
  AR = 'AR',
  Authentic = 'Authentic',
  Close = 'Close',
  Community = 'Community',
  Conscious = 'Conscious',
  Decision = 'Decision',
  Earn = 'Earn',
  EarnMoney = 'EarnMoney',
  Fake = 'Fake',
  Personalization = 'Personalization',
  Store = 'Store',
  Trash = 'Trash',
  Video = 'Video',
  VideoReview = 'VideoReview',
  VoiceAssistant = 'VoiceAssistant',
}
